### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [harupy/mlflow-extend#70]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary mlflow-extend -w /tmp/ext mlflow-extend==0.1.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting mlflow-extend==0.1.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/805/178b0284834f7/mlflow-extend-0.1.5.tar.gz (8.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-7mrp38j3/mlflow-extend/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-7mrp38j3/mlflow-extend/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-7mrp38j3/mlflow-extend/pip-egg-info
         cwd: /tmp/pip-wheel-7mrp38j3/mlflow-extend/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-7mrp38j3/mlflow-extend/setup.py", line 31, in <module>
        install_requires=get_install_requires(),
      File "/tmp/pip-wheel-7mrp38j3/mlflow-extend/setup.py", line 18, in get_install_requires
        with open(os.path.join(ROOT, "requirements.txt"), encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-7mrp38j3/mlflow-extend/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by harupy** [comment]
@thatch Thanks for reporting this. How did you get this error?

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass `--no-binary :all:`, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311
