### ISSUE TITLE
Can not import name 'mlflow' from 'mlflow_extend'

### ISSUE THREAD

**Issue by pingsutw** [harupy/mlflow-extend#99]
I just ran example in README, and got below error
- Install
```bash
pip install mlflow
pip install git+https://github.com/harupy/mlflow-extend.git
```
- Error message
```bash
python mlflow_extend.py                                                                 
Traceback (most recent call last):
  File "mlflow_extend.py", line 6, in <module>
    from mlflow_extend import mlflow
  File "/home/dslab/git/mlflow/examples/mlflow_extend.py", line 6, in <module>
    from mlflow_extend import mlflow
ImportError: cannot import name 'mlflow' from 'mlflow_extend' (/home/dslab/git/mlflow/examples/mlflow_extend.py)
```

**Comment by pingsutw** [comment]
Resolved. sorry, I set the wrong python path.
